### ISSUE TITLE
什么场景下需要使用服务端的login api

### ISSUE THREAD

**Issue by sunbiao0526** [lanceWan/wxxcx#2]
wx.login，wx.localstorage，等wx api直接可以拿到用户信息，校验是否登录等操作；
请问什么场景下，还需要经过服务端来校验登录呢？
谢谢

**Comment by lanceWan** [comment]
@sunbiao0526 这些函数是都可以获取用户信息，如果一个小程序要获取当前用户的购买商品，肯定要从服务端获取，而服务端那边需要识别当前用户是谁，所以要关联小程序用户的openid来做唯一标签。小程序虽然登录了，但服务端却并没有登录，需要小程序传递code过去，服务端来获取openid并登录关联openid的用户

**Comment by sunbiao0526** [comment]
@lanceWan 非常感谢回答。
官方api有个checkSession，需要服务端创建维护一个3rd_session，请问什么时候需要这样做呢？
小程序，默认应该也是可以维护登录状态的。
谢谢

**Comment by lanceWan** [comment]
@sunbiao0526 小程序的 `checkSession` 这个只是验证小程序登录是否有效，理论上跟服务端的session是无关的。 小程序登录之后的 `code` 给服务端，就相当于告诉服务端这个用户在小程序登录了，服务端这边自动登录这个关联的用户就好。如果用户在服务端是登录状态，就不用去处理。退出也是同样的道理

**Comment by tnevel** [comment]
请问可以用于lumen5.4吗 ？？试了一下，报如下错误！

Class 'Iwanli\Wxxcx\WxxcxServiceProvider' not found
--

**Comment by lanceWan** [comment]
不适用于 lumen  只是为Laravel写的
